export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/token/login',
    REFRESH: '/api/token/refresh',
  },
  USER_REGISTRATION: {
    REGISTER: '/api/userregistration/register',
  },
  BOOKS: {
    GET_ALL: '/api/books',
    GET_BY_ID: (id: string) => `/api/books/${id}`,
    CREATE: '/api/books',
    UPDATE: (id: string) => `/api/books/${id}`,
    DELETE: (id: string) => `/api/books/${id}`,
  },
  USERS: {
    GET_ALL: '/api/users',
    GET_PROFILE: '/api/users/profile',
    UPDATE_PROFILE: '/api/users/profile',
  },
  BOOK_ISSUES: {
    GET_ALL_ISSUES: '/api/BookIssue',
    MY_BOOKS: (userId: string) => `/api/BookIssue/user/${userId}`,
    ACTIVE_ISSUES: '/api/BookIssue/active',
    OVERDUE_ISSUES: '/api/BookIssue/overdue',
    ISSUE_BOOK: '/api/BookIssue',
    ISSUE_BY_BARCODE: '/api/BookIssue/issue-by-barcode',
    RETURN_BOOK: '/api/BookIssue/return',
    RETURN_WITH_PAYMENT: '/api/BookIssue/return-with-payment',
    GENERATE_QR_CODE: '/api/BookIssue/generate-qr-payment',
    EMAIL_RECEIPT: '/api/BookIssue/email-receipt',
    UPDATE_ISSUE: (id: string) => `/api/BookIssue/${id}`,
    DELETE_ISSUE: (id: string) => `/api/BookIssue/${id}`,
  },
  BOOK_REMINDERS: {
    SEND_DUE_REMINDERS: '/api/BookReminder/send-due-reminders',
    SEND_DUE_TODAY_REMINDERS: '/api/BookReminder/send-due-today-reminders',
    SEND_OVERDUE_REMINDERS: '/api/BookReminder/send-overdue-reminders',
    SEND_ALL_REMINDERS: '/api/BookReminder/send-all-reminders',
  },
  BOOK_RESERVATIONS: {
    REQUEST_BOOK: '/api/BookRequest',
    GET_ALL_REQUESTS: '/api/BookRequest',
    MY_REQUESTS: '/api/BookRequest/my-requests',
    GET_REQUEST: (id: string) => `/api/BookRequest/${id}`,
    APPROVE_REQUEST: (id: string) => `/api/BookRequest/${id}/approve`,
    REJECT_REQUEST: (id: string) => `/api/BookRequest/${id}/reject`,
    PICKUP_COMPLETE: (id: string) => `/api/BookRequest/${id}/pickup-complete`,
    CANCEL_REQUEST: (id: string) => `/api/BookRequest/${id}`,
    RESERVE_BOOK: '/api/BookReservation',
    GET_ALL_RESERVATIONS: '/api/BookReservation',
    DEBUG_RESERVATIONS: '/api/BookReservation/debug',
    MY_RESERVATIONS: '/api/BookReservation/my-reservations',
    GET_RESERVATION: (id: string) => `/api/BookReservation/${id}`,
    NOTIFY_AVAILABLE: (id: string) => `/api/BookReservation/${id}/notify-available`,
    AUTO_NOTIFY_AVAILABLE: '/api/BookReservation/auto-notify-available',
    SEND_PICKUP_REMINDERS: '/api/BookReservation/send-pickup-reminders',
    NOTIFY_BOOK_RETURNED: (bookId: string) => `/api/BookReservation/notify-book-returned/${bookId}`,
    COMPLETE_PICKUP: (id: string) => `/api/BookReservation/${id}/complete-pickup`,
    CANCEL_RESERVATION: (id: string) => `/api/BookReservation/${id}/cancel`,
    GET_USER_RESERVATIONS: (userId: string) => `/api/BookReservation/user/${userId}`,
  },
  BOOK_COPIES: {
    GET_BY_BOOK: (bookId: string) => `/api/BookCopy/book/${bookId}`,
    GET_BY_BARCODE: (barcode: string) => `/api/BookCopy/barcode/${barcode}`,
    CREATE_MULTIPLE: '/api/BookCopy/multiple',
  },
  CATEGORIES: {
    GET_ALL: '/api/BookCategory',
    GET_BY_ID: (id: string) => `/api/BookCategory/${id}`,
    CREATE: '/api/BookCategory',
    UPDATE: (id: string) => `/api/BookCategory/${id}`,
    DELETE: (id: string) => `/api/BookCategory/${id}`,
  },
  USER_MANAGEMENT: {
    GET_ALL_USERS: '/api/UserManagement',
    GET_USER: (id: string) => `/api/UserManagement/${id}`,
    UPDATE_USER: (id: string) => `/api/UserManagement/${id}`,
    DELETE_USER: (id: string) => `/api/UserManagement/${id}`,
  },
  FINES: {
    GET_ALL: '/api/Fine/get-all',
    GET_OVERDUE: '/api/Fine/get-overdue',
    GET_BY_USER: (userId: string) => `/api/Fine/get-by-user/${userId}`,
    WAIVE_FINE: (id: string) => `/api/Fine/waive/${id}`,
    ADJUST_FINE: (id: string) => `/api/Fine/adjust/${id}`,
    CALCULATE_FINE: (issueId: string) => `/api/Fine/calculate/${issueId}`,
    GET_ALL_FINES: '/api/Fine/all',
    GET_OVERDUE_FINES: '/api/Fine/overdue',
    GET_USER_FINES: (userId: string) => `/api/Fine/user/${userId}`,
    CALCULATE_FINE_GET: (issueId: string) => `/api/Fine/calculate/${issueId}`,
  },
  PAYMENTS: {
    GET_ALL: '/api/FinePayment/get-all',
    GET_BY_USER: (userId: string) => `/api/FinePayment/get-by-user/${userId}`,
    PAY_FINE: (id: string) => `/api/FinePayment/pay/${id}`,
    PROCESS_PAYMENT: '/api/FinePayment/process',
    PROCESS_ONLINE_PAYMENT: '/api/FinePayment/process-online',
    PROCESS_OFFLINE_PAYMENT: '/api/FinePayment/process-offline',
    GET_PAYMENT_HISTORY: '/api/FinePayment/get-history',
    GET_RECEIPT: (paymentId: string) => `/api/FinePayment/get-receipt/${paymentId}`,
    GET_LIBRARIAN_COLLECTIONS: '/api/FinePayment/librarian-collections',
  },
  FINE_PAYMENTS: {
    GET_ALL: '/api/FinePayment/get-all',
    CREATE: '/api/FinePayment/create',
    GET_BY_ID: (id: string) => `/api/FinePayment/get-by-id/${id}`,
    UPDATE: (id: string) => `/api/FinePayment/update/${id}`,
    DELETE: (id: string) => `/api/FinePayment/delete/${id}`,
    GET_BY_FINE: (fineId: string) => `/api/FinePayment/get-by-fine/${fineId}`,
  },
  LIBRARY_SETTINGS: {
    GET: '/api/LibrarySettings',
    UPDATE: '/api/LibrarySettings',
    GET_BY_LIBRARY: (libraryId: string) => `/api/LibrarySettings/library/${libraryId}`,
  },
  NOTIFICATIONS: {
    GET_ALL: '/api/Notification',
    GET_RECENT: '/api/Notification/recent',
    CREATE: '/api/Notification',
    MARK_READ: (id: string) => `/api/Notification/${id}/read`,
    DELETE: (id: string) => `/api/Notification/${id}`,
    SEND_ANNOUNCEMENT: '/api/Notification/announcement',
    GET_USER_NOTIFICATIONS: (userId: string) => `/api/Notification/user/${userId}`,
  },
  REVIEWS: {
    GET_ALL: '/api/Review',
    GET_BY_BOOK: (bookId: string) => `/api/Review/book/${bookId}`,
    CREATE: '/api/Review',
    UPDATE: (id: string) => `/api/Review/${id}`,
    DELETE: (id: string) => `/api/Review/${id}`,
    GET_BY_USER: (userId: string) => `/api/Review/user/${userId}`,
  },
  DIGITAL_CONTENT: {
    GET_ALL: '/api/DigitalContent',
    GET_BY_ID: (id: string) => `/api/DigitalContent/${id}`,
    GET_BY_TYPE: (type: string) => `/api/DigitalContent/type/${type}`,
    DOWNLOAD: (id: string) => `/api/DigitalContent/${id}/download`,
  },
  RECOMMENDATIONS: {
    GET_FOR_USER: (userId: string) => `/api/Recommendation/user/${userId}`,
    GET_POPULAR: '/api/Recommendation/popular',
    GET_RECENT: '/api/Recommendation/recent',
  },
  WISHLIST: {
    GET_USER_WISHLIST: (userId: string) => `/api/Wishlist/user/${userId}`,
    ADD_TO_WISHLIST: '/api/Wishlist',
    REMOVE_FROM_WISHLIST: (id: string) => `/api/Wishlist/${id}`,
  },
  USER_DASHBOARD: {
    GET_STATISTICS: (userId: string) => `/api/UserDashboard/statistics/${userId}`,
  },
  LIBRARIAN_DASHBOARD: {
    GET_STATISTICS: '/api/LibrarianDashboard/statistics',
  },
  PROFILE: {
    GET: '/api/Profile/get-profile',
    UPDATE: '/api/Profile/update-profile',
    CHANGE_PASSWORD: '/api/Profile/change-password',
  },
} as const;